/*
 * This file is generated by jOOQ.
 */
package com.mgzk.projectjooq.domain;


import com.mgzk.projectjooq.domain.tables.Post;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.POST</code>.
     */
    public static final Post POST = Post.POST;
}
